---
title: Persistent Volumes backups
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/persistent-volumes-backups
folder: che-7/administration-guide
summary:
---

:parent-context-of-persistent-volumes-backups: {context}

[id='persistent-volumes-backups']
= Persistent Volumes backups

link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Persistent Volumes] are used for storing the {prod-id-short} workspace data like source code, scripts, documentation. 
In order to prevent the data loss Persistent Volumes should be backed up periodically. It is not recommended to use backup solutions which are dependednt on the underlying storage system i.e. link:https://www.gluster.org/[Gluster] / link:https://ceph.io[https://ceph.io] specific.
The recomendation is to use the storage agonstic tools for back up and restoring the Kubernetes cluster resources and persistent volumes.
Currently, the recomended way for backing up Kubernetes applications and their persistent volumes is link:https://github.com/vmware-tanzu/velero[velero] which can:

- Take backups of the cluster and restore in case of loss.
- Migrate cluster resources to other clusters.
- Replicate the production cluster to development and testing clusters.
